import type { NextPage } from 'next'
import Head from 'next/head'
import Banner from '../components/banner'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Coffee Shop</title>
        <meta name="description" content="Generated by Coffee Shop" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
     
        <Banner buttonText='hello' handleOnClick={()=>alert('clicked')}/>

      </main>

  
    </div>
  )
}

export default Home
